export const NOTI_READY_TO_BUY = 'Ready to buy product'
export const NOTI_GREATER_THAN_ONE = 'Quantity must equal or greater than 1'
export const NOTI_ACT_ADD = 'Added successful !!!'
export const NOTI_ACT_UPDATE = 'Update successfull !!!'
export const NOTI_ACT_DELETE = 'Deleted successfull !!!'
export const CARTS_FROM_LOCAL_STORAGE = 'carts'
export const NOTI_EMPTY_PRODUCT = 'Empty product in your cart'